spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URL}
  application:
    name: event-service
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
server:
  port: 8085

springdoc:
  swagger-ui:
    path: /

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_CLIENT_URI}

client:
  base-url: ${GATEWAY_URL}
  organization:
    url: ${client.base-url}/organization
    value: organization-service
